server:
  port: 8003

spring:
  application:
    name: aliyun-video-upload
  profiles:
    active: dev
#文件上传的相关设置
  servlet:
    multipart:
      enabled: true #默认为true
      max-file-size: 10MB #设置单个文件的上传大小
      max-request-size: 30MB #设置上传文件的总大小
  #将edu_service注册到nacos服务注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#暴露所有的监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #设置不检查redis的健康状态，因为还没用到redis
  health:
    redis:
      enabled: false

#阿里云 OSS配置信息
aliyun:
  vod:
    file:
      keyid: LTAI5tHuNsemaiLnP3yro4vD #访问id
      keysecret: ed1Zxok1SklTEI40HhRKkJeRcQdyWc #访问密码
