server:
  port: 8010

spring:
  application:
    name: online-edu-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: service-edu # 路由的ID，没有固定规则但要求必须唯一，建议配置服务名
          uri: lb://service-edu  #匹配后提供服务的动态路由地址
          predicates:
            - Path=/serviceedu/** #断言，路径相匹配的进行路由
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/** #断言，路径相匹配的进行路由
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/servicecms/** #断言，路径相匹配的进行路由
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/servicedaily/** #断言，路径相匹配的进行路由
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/serviceoss/** #断言，路径相匹配的进行路由
        - id: service-comment
          uri: lb://service-comment
          predicates:
            - Path=/servicecomment/** #断言，路径相匹配的进行路由
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/servicemsm/** #断言，路径相匹配的进行路由
        - id: server-order
          uri: lb://server-order
          predicates:
            - Path=/serviceorder/** #断言，路径相匹配的进行路由
        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/serviceusercenter/**,/api/ucenter/wx/** #匹配多个路径使用,逗号分隔
        - id: aliyun-video-upload
          uri: lb://aliyun-video-upload
          predicates:
            - Path=/servicevod/** #断言，路径相匹配的进行路由





